version: '3.0'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - '.env'
  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo
