version: '3.0'

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - '.env'

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
