version: '3.0'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - '.env'

  server:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    entrypoint: uvicorn main:app --proxy-headers --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - mongo

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus/
    container_name: prometheus
    hostname: prometheus
    depends_on:
      - server
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    user: root
    depends_on:
      - prometheus
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
