version: 1
disable_existing_loggers: false

filters:
  # See https://github.com/snok/asgi-correlation-id#configure-logging
  correlation_id:
    (): asgi_correlation_id.CorrelationIdFilter
    uuid_length: 8
    default_value: '-'

formatters:
  timestamped:
    format: '%(asctime)s - %(correlation_id)s - %(levelname)s - %(name)s - %(message)s'

handlers:
  main:
    class: logging.StreamHandler
    formatter: timestamped
    filters: [correlation_id]
    stream: ext://sys.stdout

loggers:
  '':
    handlers: [main]
    level: INFO
    propagate: false
